// server/utils/topics.js - EXPANDED VERSION
module.exports = [
  // Core Political Topics
  "US politics",
  "election integrity",
  "voting rights",
  "gerrymandering",
  "campaign finance",
  "lobbying corruption",
  "political polarization",
  "constitutional crisis",
  "federal overreach",
  "states rights",
  "judicial activism",
  "supreme court politics",
  "congressional corruption",
  "executive power",
  "impeachment politics",

  // Global Affairs & Security
  "foreign affairs",
  "military industrial complex",
  "defense spending",
  "foreign interventions",
  "regime change operations",
  "proxy wars",
  "arms trafficking",
  "war profiteering",
  "NATO expansion",
  "nuclear policy",
  "cyber warfare",
  "space militarization",
  "intelligence agencies",
  "national security state",
  "homeland security",

  // Economy & Finance
  "global economy",
  "financial crimes",
  "market manipulation",
  "cryptocurrency",
  "central banking",
  "inflation policy",
  "currency wars",
  "trade wars",
  "economic sanctions",
  "derivatives fraud",
  "offshore banking",
  "tax evasion",
  "wealth inequality",
  "universal basic income",
  "digital currencies",
  "economic collapse",

  // Technology & Digital Rights
  "tech regulation",
  "surveillance state",
  "digital privacy",
  "AI ethics",
  "algorithmic governance",
  "tech monopolies",
  "social media censorship",
  "net neutrality",
  "data governance",
  "facial recognition",
  "biometric surveillance",
  "digital ID systems",
  "internet freedom",
  "cyber security",
  "quantum computing",
  "automation & jobs",
  "technological singularity",

  // Social Justice & Rights
  "civil rights",
  "racial justice",
  "police reform",
  "criminal justice reform",
  "prison industrial complex",
  "death penalty",
  "drug policy reform",
  "immigration policy",
  "refugee crisis",
  "human trafficking",
  "labor rights",
  "union organizing",
  "worker exploitation",
  "gig economy",
  "minimum wage",
  "healthcare rights",
  "housing crisis",
  "homelessness",

  // Culture & Society
  "free speech",
  "media bias",
  "misinformation & propaganda",
  "culture wars",
  "cancel culture",
  "woke ideology",
  "religious freedom",
  "gender politics",
  "reproductive rights",
  "LGBTQ+ rights",
  "parental rights",
  "education policy",
  "school choice",
  "critical race theory",
  "book banning",
  "academic freedom",
  "social engineering",

  // Health & Medicine
  "medical freedom",
  "pharmaceutical corruption",
  "vaccine mandates",
  "public health policy",
  "medical censorship",
  "hospital protocols",
  "mental health crisis",
  "addiction epidemic",
  "healthcare costs",
  "medical monopolies",
  "alternative medicine",
  "health surveillance",
  "bioweapons research",
  "gain of function",
  "pandemic preparedness",

  // Environment & Energy
  "climate policy",
  "environmental collapse",
  "carbon taxation",
  "green new deal",
  "renewable energy",
  "nuclear energy",
  "fossil fuel industry",
  "energy independence",
  "water scarcity",
  "pollution control",
  "wildlife conservation",
  "deforestation",
  "ocean acidification",
  "geoengineering",
  "environmental justice",

  // Corporate Power & Control
  "corporate overreach",
  "regulatory capture",
  "monopoly power",
  "antitrust enforcement",
  "corporate welfare",
  "public-private partnerships",
  "corporate censorship",
  "ESG investing",
  "stakeholder capitalism",
  "corporate governance",
  "supply chain control",
  "food monopolies",
  "media consolidation",
  "pharmaceutical cartels",
  "defense contractors",

  // Emerging Issues
  "transhumanism",
  "genetic engineering",
  "bioethics",
  "space colonization",
  "artificial general intelligence",
  "neural interfaces",
  "digital consciousness",
  "simulation theory",
  "consciousness studies",
  "life extension",
  "nanotechnology",
  "robotics ethics",
  "virtual reality",
  "augmented reality",
  "metaverse governance",

  // Collapse & Preparedness
  "societal collapse",
  "economic collapse",
  "infrastructure failure",
  "supply chain collapse",
  "food security",
  "water security",
  "energy security",
  "grid vulnerability",
  "cyber attacks",
  "natural disasters",
  "pandemic preparedness",
  "community resilience",
  "self-sufficiency",
  "survivalism",
  "prepper movement",

  // Conspiracy & Hidden Power
  "deep state operations",
  "shadow governance",
  "secret societies",
  "elite networks",
  "conspiracy theories",
  "false flag operations",
  "psychological operations",
  "mind control",
  "mass surveillance",
  "social control",
  "population control",
  "agenda 2030",
  "great reset",
  "world economic forum",
  "globalist agenda",
];
